run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - dupl
    - errorlint
    - gofmt
    - goimports
    - gomodguard
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - unused
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  gomodguard:
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - errors
              - fmt
  dupl:
    threshold: 400
